name=pinch
version=1.0
author=moddo
maintainer=moddo <hi@moddo.io>
sentence=Board-specific examples and utilities for the moddo pinch.
paragraph=
category=Other
url=https://github.com/moddoio
architectures=samd
license=LGPL-2.1-or-later
